spring:
  application:
    name: mybatis-plus-example
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always

springdoc:
  swagger-ui.path: /swagger-ui.html

mybatis-plus:
  type-handlers-package: com.mflyyou.handler